# Generated by Django 5.1.7 on 2025-05-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('for upload', ' For Upload'), ('for claim', 'For Claim')], max_length=10),
        ),
    ]
