# Generated by Django 5.1.7 on 2025-04-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_note_delete_react'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('hygiene', 'Hygiene'), ('clothing', 'Clothing'), ('accessories', 'Accessories'), ('documents', 'Documents'), ('stationery', 'Stationery'), ('sports', 'Sports Equipment'), ('toys', 'Toys'), ('food', 'Food/Drink'), ('tools', 'Tools'), ('pet_items', 'Pet Items'), ('medical', 'Medical Items'), ('musical', 'Musical Instruments'), ('others', 'Others')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10)),
            ],
        ),
    ]
