# Generated by Django 5.1.7 on 2025-05-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_item_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_claimed',
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending Review'), ('claimed', 'Claimed')], default='pending', max_length=10),
        ),
    ]
