# Generated by Django 5.1.7 on 2025-05-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending Review'), ('claimed', 'Claimed')], default='available', max_length=10),
        ),
    ]
