# Generated by Django 5.1.7 on 2025-04-28 16:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_claim_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='claim',
            unique_together={('item', 'user')},
        ),
    ]
