# Generated by Django 5.2 on 2025-05-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_claim_date_claim_approval_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('hygiene', 'Hygiene'), ('clothing', 'Clothing'), ('accessories', 'Accessories'), ('documents', 'Documents'), ('stationery', 'Stationery'), ('sports', 'Sports Equipment'), ('toys', 'Toys'), ('tools', 'Tools'), ('pet_items', 'Pet Items'), ('medical', 'Medical Items'), ('musical', 'Musical Instruments'), ('others', 'Others')], max_length=50),
        ),
    ]
